### PR TITLE
Fix unit test

### PR DESCRIPTION
**Pull request by koenderks**

### CODE REVIEW

**Comment by vandenman** [comment]
as a test, can you remove the `	skip("Does not reproduce on Linux")` calls and see if the tests still pass? The latest BAIN update on CRAN fixed some things with the RNG not being reproducible across OSes.

**Comment by vandenman** [comment]
well it looks like that didn't work :sweat_smile: the first commit also failed though, any idea why?

**Comment by koenderks** [comment]
I think they are at least consistent now (but all incorrect haha), I'll try to remake all the tests on my machine and check if the new outcomes are consistent across platforms

**Comment by koenderks** [comment]
Alright they work now except for 2 tests for the path diagram plots. Can you reproduce these deviations @vandenman? I cannot on my end.

**Pull request merged**
