### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by koenderks**
Addresses:

- For the t-tests: Welch, paired, and one-sample everything should stay the same as before the added column. The bold note should never be given there. Also, there should not be an attempt to show the pie-chard for PMPc, which often goes wrong.
- If in ANOVA, ANCOVA, REGRESSION, SEM, the bold note is given then the pie-chards are not shown because PMPc is not calculated then. But the pie-chards for PMPa and PMPb could be shown.

### CODE REVIEW

**Comment by amirmasoudabdol** [comment]
I added this to the 0.16.1 since it seems to be a minor bug fix.

**Comment by koenderks** [comment]
Thanks, I wanted to do this myself but for some reason I cannot see or assign any projects anymore.

**Comment by Kucharssim** [comment]
The code looks ok, but are there any issues to be linked to this PR? What should I check to see whether the bugs are fixed? @koenderks

**Comment by amirmasoudabdol** [comment]
@koenderks, oh, I think I recall that you have added things to the project before, maybe I'm wrong, either way I'm going to check! :-)

**Comment by koenderks** [comment]
@Kucharssim Yeah sorry, Herbert send me some comments by e-mail. I've added them to the description of this PR.

**Comment by koenderks** [comment]
@amirmasoudabdol Could it be because (I got an email) I was removed from the contributors?

**Comment by amirmasoudabdol** [comment]
@koenderks, yes, I see that Alex has changed a few things around Teams and Projects, and you can only read them at the moment.

**Review by Kucharssim — APPROVED** [review]
lgtm!

**Pull request merged**
